### ISSUE TITLE
ScrapBookMark can't load Companion, which displays "Network Error"

### ISSUE THREAD

**Issue by dryquart** [OkorieWare/ScrapBookMark-standard#1]
As reported on Firefox Extensions: After installing ScrapBookMark 1.0.8, it reports Error 409 and "ScrapBookMark companion is required" for Firefox 107 under Windows 7. Additionally, Companion reports "Network Error - unable to contact network. Companion will now close." This was after following the instructions in the extension.
- Ran the Companion
- Closed the browser or Reload extenstion (tried both)
- Companion was still not recognized by SBM Standard.
- Temporarily disabling anti-virus and Internet security apps as well as the Windows firewall, still results in "Error 409" and the Companion dialog is still displayed with the "Network Error...." message.
I will remove/update my post from the FF Extensions page according to your feedback.
Are there any log files generated that I could attach?

**Comment by OkorieWare** [comment]
I have tested ScrapBookMark Companion, and it is fully functional.

If you have rule out your firewall and your network, your ISP region is the likely culprit. ScrapBookMark Companion relies on Google Cloud Platform services, under which, some regions are currently unsupported.

**Comment by dryquart** [comment]
Google Cloud Platform services are not blocked by my ISP in my location. If you can not give me a clue how to debug this problem or generate log files for review, then one out of the current four users, or 25%, can not use this, which is unfortunate because I quite liked ScrapBook legacy.

**Comment by OkorieWare** [comment]
I've put some leniency on my server side firewall; Something that, but for the sake of diagnosis, I'm very hesitant to do (due to a recent increase in hackers / malicious bots traffic).

Let me know if it works out for you.

**Comment by dryquart** [comment]
I have made some headway after re-installing the Companion, starting it up, and leaving it open while Firefox loads. Unfortunately, after entering valid values for all the Settings, I get a "Service Error - unable to start background service" error message from the Companion upon "Save Settings and Start Service". As a result, the Settings are not saved.

**Comment by OkorieWare** [comment]
That error occurs if the required port is already claimed by another program.
Default port on Windows is 88, and 8888 on Linux and Mac.

Go to the options page, and Ctrl+Click on Reload; Ctrl+Shift+Click on Reset.

After that, go to the options page, Click on Settings, and try a different port that you know is free.

**Comment by dryquart** [comment]
Well, I give up. Even on open ports and disabling the firewall doesn't resolve the Error 401. Just not worth putting anymore effort into this. Thanks anyway.

**Comment by OkorieWare** [comment]
For what it's worth, I think you were almost at the finish line.

I don't know if you've watched the tutorial video.
Here's an excerpt from the usage page...
```
Error 401
- Go to Settings, select the location where you want all your pages to be saved, then click the Save and Start Server button.
- Make sure you create a sub-folder for this location in order to avoid clutter.
```

**Comment by dryquart** [comment]
No, I have watched no tutorial. I couldn't resolve the Error 401 because the "background service" could not be started after entering the folders in the Settings. I disabled the firewall, tried other open ports besides 88, but it was hopeless. I still got the message that the background service could not be started.

**Comment by OkorieWare** [comment]
I'm sorry to here that.
Having tested it on my end, successfully on three different platforms (windows, linux, mac), I too am at a loss.
